FROM debian
COPY index.html /var/www/html/index.html
COPY init.sh /init.sh
RUN apt-get update && apt-get install -y nginx && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN chmod 700 /init.sh
EXPOSE 80
CMD ["/init.sh"]
